name: post_rating

services:
  app:
    container_name: post_rating_app
    image: post_rating_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py migrate
      && gunicorn --workers=3 --timeout=600 --bind=0.0.0.0:8000 core.wsgi:application"
    depends_on:
      - postgres
      - redis
    env_file:
      - .compose/config.env
    networks:
      - post-rating
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - app-data:/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    container_name: post_rating_postgres
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: post_rating
    networks:
      - post-rating
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

  celery:
    container_name: post_rating_celery
    image: post_rating_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "celery -A core.celery worker -l INFO"
    depends_on:
      - postgres
      - redis
    env_file:
      - .compose/config.env
    networks:
      - post-rating
    restart: always

  redis:
    container_name: post_rating_redis
    image: redis:7.2
    command: [ "redis-server", "--requirepass", "redis_password" ]
    networks:
      - post-rating
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

networks:
  post-rating:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  app-data: